export const ACTION_QUIZ = {
  START_QUIZ: "START_QUIZ",
  SET_QUESTION: "SET_QUESTION",
  SET_QUIZES: "SET_QUIZES",
};

export const ACTION_USER = {
  SET_USER: "SET_USER",
  ADD_ANSWER: "ADD_ANSWER",
  NEXT_QUESTION: "NEXT_QUESTION",
  FINISH_QUIZ: "FINISH_QUIZ",
};
