export const ACTION_QUIZ = {
  START_QUIZ: "START_QUIZ",
  SET_QUIZES: "SET_QUIZES",
  SET_NEXT_QUESTION: "SET_NEXT_QUESTION",
  SET_IS_ANSWERED: "SET_IS_ANSWERED",
  CLEAR_QUIZ: "CLEAR_QUIZ",

  ADD_ANSWER: "ADD_ANSWER",
  ADD_QUESTION: "ADD_QUESTION",

  DELETE_ANSWER: "DELETE_QUESTION",
  DELETE_QUESTION: "DELETE_QUESTION",

  CREATE_NEW_QUIZ: "CREATE_NEW_QUIZ",
  NEW_QUESTION: "NEW_QUESTION",
  NEW_ANSWER: "NEW_ANSWER",
};

export const ACTION_USER = {
  SET_USER: "SET_USER",
  ADD_ANSWER: "ADD_ANSWER",
  NEXT_QUESTION: "NEXT_QUESTION",
  FINISH_QUIZ: "FINISH_QUIZ",
  SET_RESULTS: "SET_RESULTS",
  CLEAR_ANSWERS: "CLEAR_ANSWERS",
};

export const TIME_TO_ANSWER = 10;
