// Quiz

export const ACTION_QUIZ = {
  START_QUIZ: "START_QUIZ",
  SET_QUIZES: "SET_QUIZES",
  SET_NEXT_QUESTION: "SET_NEXT_QUESTION",
  SET_IS_ANSWERED: "SET_IS_ANSWERED",
  CLEAR_QUIZ: "CLEAR_QUIZ",

  WRITE_ANSWER: "WRITE_ANSWER",

  //--------------- Quiz creating ----------------

  CREATE_QUIZ: "CREATE_QUIZ",
  SET_SELECTED_CARD: "SET_SELECTED_CARD",

  NEW_QUESTION: "NEW_QUESTION",
  NEW_ANSWER: "NEW_ANSWER",

  ADD_ANSWER: "ADD_ANSWER",
  ADD_QUESTION: "ADD_QUESTION",

  UPDATE_ANSWER: "UPDATE_ANSWER",
  UPDATE_QUESTION: "UPDATE_QUESTION",

  DELETE_ANSWER: "DELETE_ANSWER",
  DELETE_QUESTION: "DELETE_QUESTION",

  CREATE_NEW_QUIZ: "CREATE_NEW_QUIZ",
};

// User

export const ACTION_USER = {
  REGISTERED: "REGISTERED",
  LOGGED_IN: "LOGGED_IN",
  LOGGED_OUT: "LOGGED_OUT",

  SET_USER: "SET_USER",
  ADD_ANSWER: "USER_ADD_ANSWER",
  NEXT_QUESTION: "NEXT_QUESTION",
  FINISH_QUIZ: "FINISH_QUIZ",
  SET_RESULTS: "SET_RESULTS",
  CLEAR_ANSWERS: "CLEAR_ANSWERS",
};

export const TIME_TO_ANSWER = 10;
